config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'books/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get'top' => 'root#top'

  post'books' => 'books#create'

  get'books' => 'books#index'

  get'books/:id' => 'books#show', as: 'book'

  get'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete'books/:id' => 'books#destroy', as: 'destroy_book'

  root to: 'home#index'

  # resourses :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    if book.save
    flash[:notice] = "Book was successfully created"
    redirect_to book_path(book.id)
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
    flash[:notice] = "Book was successfully updated"
    end
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to books_path
    end
  end

  private

  def book_params
   params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

def top
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for @book,url: update_book_path(@book) do |f| %>
    <h4> Title</h4>
    <%= f.text_field :title %>
    <h4> Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>

    <span>
	<%=link_to "Show" ,books_path %>
    </span>
    <span>
	<%=link_to "Back" ,books_path %>
    </span>


<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h1>Books</h1>

<table>
	<thead>
		<tr>
			<th> Title</th>
			<th> Body</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to 'Show', book_path(book.id) %></td>
			<td><%= link_to "Edit", edit_book_path(book.id) %></td> 
			<td><%= link_to "Delete", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %><td>
		</tr>
		<% end %>
	</tbody>
</table>

<h1>New Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
 
    <h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>Body</h4>
    <%= f.text_area :body %>
 
    <%= f.submit 'Create Book' %>
 
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%=link_to "Back" ,books_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>WebCampBackendNew</title>
  <meta name="csrf-param" content="authenticity_token">
  <meta name="csrf-token" content="jWp2LUAHqq1AvStqwe+tFsJxrahisJjOPx+wSK91w7vCaJ2za9WBDzA7Z0C0qCSQEUj6P9FafWLx9fzBuE13bw==">
</head>
<body>
	<h1>
		"ようこそ"
		<strong>Bookers</strong>
		"へ！"
	</h1>
	<p>
		<storog>Bookers</storog>
		"ではさまざまな書籍に関するあなたの意見や"
	</p>
	<p>印象を共有し交換することができます</p>
		 <span>
            <%=link_to "Start" ,books_path %>
         </span>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/top.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.css">
  <title>WebCampBackendNew</title>
  <meta name="csrf-param" content="authenticity_token">
  <meta name="csrf-token" content="jWp2LUAHqq1AvStqwe+tFsJxrahisJjOPx+wSK91w7vCaJ2za9WBDzA7Z0C0qCSQEUj6P9FafWLx9fzBuE13bw==">
</head>
<body>
	<h1>
		"ようこそ"
		<strong>Bookers</strong>
		"へ！"
	</h1>
	<p>
		<storog>Bookers</storog>
		"ではさまざまな書籍に関するあなたの意見や"
	</p>
	<p>印象を共有し交換することができます</p>
		 <span>
            <%=link_to "Start" ,books_path %>
         </span>
</body>
</html>